spring.application.name=sreepooja

spring.datasource.url=jdbc:mysql://localhost:3306/sreepooja
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.jackson.time-zone=Asia/Kolkata

jwt.secret=ce2d06b33a35eda6b3e0df53c05633002b3474e730a9929f07eb8db832656bc4


spring.web.resources.static-locations=classpath:/static/,file:./uploads/

# Enable multipart
spring.servlet.multipart.enabled=true

# Increases the allowed number of multipart parts (files + form fields)
server.tomcat.max-part-count=100

# Increase the maximum number of parts/files in the request (e.g., 50)
#spring.servlet.multipart.max-request-parts=50

app.upload.base-path=uploads

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


#razonr pay
razorpay.key.id= rzp_test_Sr7e3cxuLQjO3S
razorpay.key.secret= lWPQjfDgdk1rvDHbm4PMMUjH

#superadmin
super-admin.first-name=Super
super-admin.last-name=Admin
super-admin.mobile-no=9876543210
super-admin.password=Superadmin@123